spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://tp1-db1:5432/db"
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
